[versions]
agp = "8.13.1"
androidsvg = "1.4"
appcompat = "1.7.1"
browser = "1.9.0"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
glide = "5.0.5"
gridlayout = "1.1.0"
kotlin = "2.2.21"
material = "1.14.0-alpha06"
maven = "0.34.0"
media3 = "1.8.0"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
rssparser = "6.1.1"
swiperefreshlayout = "1.1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven" }

[libraries]
androidsvg = { module = "com.caverock:androidsvg", version.ref = "androidsvg" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
material = { module = "com.google.android.material:material", version.ref = "material" }
rssparser = { module = "com.prof18.rssparser:rssparser", version.ref = "rssparser" }